@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant ":DeletePersonCommandParser" as DeletePersonCommandParser LOGIC_COLOR
participant "d:DeletePersonCommand" as DeletePersonCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete [p] 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("delete [p] 1")
activate AddressBookParser

create DeleteCommandParser
AddressBookParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> AddressBookParser
deactivate DeleteCommandParser

AddressBookParser -> DeleteCommandParser : parse("[p] 1")
activate DeleteCommandParser

create DeletePersonCommandParser
DeleteCommandParser -> DeletePersonCommandParser
activate DeletePersonCommandParser

create DeletePersonCommand
DeletePersonCommandParser -> DeletePersonCommand : parse(1)
activate DeletePersonCommand


DeletePersonCommand -> DeletePersonCommandParser : d
deactivate DeletePersonCommand

DeletePersonCommandParser --> DeleteCommandParser : d
deactivate DeletePersonCommandParser

DeleteCommandParser --> AddressBookParser : d
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> AddressBookParser
destroy DeleteCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> DeletePersonCommand : execute(model)
activate DeletePersonCommand

DeletePersonCommand -> Model : deletePerson(person)
activate Model

Model --> DeletePersonCommand
deactivate Model

create CommandResult
DeletePersonCommand -> CommandResult
activate CommandResult

CommandResult --> DeletePersonCommand
deactivate CommandResult

DeletePersonCommand --> LogicManager : result
deactivate DeletePersonCommand

[<--LogicManager
deactivate LogicManager
@enduml
