@startuml
!include style.puml


box Logic LOGIC_COLOR_T1
participant ":FindCommandParser" as FindCommandParser LOGIC_COLOR
participant ":FindPersonCommandParser" as FindPersonCommandParser LOGIC_COLOR
participant "f:FindPersonCommand" as FindPersonCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":PersonContainsKeywordsPredicate" as PersonContainsKeywordsPredicate MODEL_COLOR
end box

[-> FindCommandParser : parse("[p] g/n/alex g/n/tan")
activate FindCommandParser

FindCommandParser -> FindCommandParser : checkValidGroups()
activate FindCommandParser
FindCommandParser --> FindCommandParser
deactivate FindCommandParser

create FindPersonCommandParser
FindCommandParser -> FindPersonCommandParser
activate FindPersonCommandParser
FindPersonCommandParser --> FindCommandParser
deactivate FindPersonCommandParser

FindCommandParser -> FindPersonCommandParser : parse(["n/alex", "n/tan"])
activate FindPersonCommandParser

create PersonContainsKeywordsPredicate
FindPersonCommandParser -> PersonContainsKeywordsPredicate
activate PersonContainsKeywordsPredicate
PersonContainsKeywordsPredicate --> FindPersonCommandParser
deactivate PersonContainsKeywordsPredicate

create FindPersonCommand
FindPersonCommandParser -> FindPersonCommand
activate FindPersonCommand
FindPersonCommand --> FindPersonCommandParser : f
deactivate FindPersonCommand

FindPersonCommandParser --> FindCommandParser : f
deactivate FindPersonCommandParser
[<-[hidden]- FindPersonCommandParser
destroy FindPersonCommandParser

[<-- FindCommandParser : f
deactivate FindCommandParser

[<-[hidden]- FindCommandParser
destroy FindCommandParser

[-> FindPersonCommand : execute()
activate FindPersonCommand

FindPersonCommand -> Model : updateFilteredPersonList()
activate Model
Model --> FindPersonCommand
deactivate Model

create CommandResult
FindPersonCommand -> CommandResult
activate CommandResult
CommandResult --> FindPersonCommand
deactivate CommandResult

[<-- FindPersonCommand : result
deactivate FindPersonCommand

@enduml
