@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Logic {

Class AddressBookParser
Class XYZCommand
Class "{abstract}\nXYZCommand" as XYZAbstractCommand
Class CommandResult
Class "{abstract}\nCommand" as Command
Class XYZTYPECommand

Class "<<interface>>\nLogic" as Logic
Class LogicManager
}

package Model{
Class HiddenModel #FFFFFF
}

package Storage{
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Logic

LogicManager .right.|> Logic
LogicManager -right->"1" AddressBookParser
AddressBookParser ..> XYZCommand : creates >
AddressBookParser ..> XYZTYPECommand : creates >

XYZAbstractCommand -up-|> Command
XYZCommand -left-|> Command
LogicManager ..> Command : executes >
XYZTYPECommand -up-|> XYZAbstractCommand

LogicManager --> Model
LogicManager --> Storage
Storage --[hidden] Model
Command .[hidden]up.> Storage
Command .right.> Model
note right of XYZAbstractCommand: e.g. AddCommand, \nFindCommand
note right of XYZCommand: e.g. HelpCommand, \nExitCommand
note right of XYZTYPECommand: e.g. AddPersonCommand, \n FindTaskCommand

Logic ..> CommandResult
LogicManager .down.> CommandResult
Command .up.> CommandResult : produces >
@enduml
